# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    wget https://gnome.mirror.digitalpacific.com.au/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip -OutFile C:\gtk.zip
    Expand-Archive -Path C:\gtk.zip -DestinationPath C:\GTK
    npm install
    npm run build
  displayName: 'npm install and build'
